os:
  - linux
  - osx
osx_image:
  - xcode9.2
  - xcode10.1
language: c
compiler: clang
script:
  - cp Makefiles/sledconf.ci ./sledconf
  - make -j
  - ./sled
env:
  - ASAN_OPTIONS="detect_odr_violation=1"
sudo: required
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/44f13e0bc931c8763a5c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
